name: Create Release for Salesforce
'on':
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: v1.0.0
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          tag_name: '${{ github.event.inputs.version }}'
          release_name: 'Salesforce Release ${{ github.event.inputs.version }}'
          draft: false
          prerelease: false
      - name: Upload Package to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: '${{ steps.create-release.outputs.upload_url }}'
          asset_path: salesforce-package.zip
          asset_name: salesforce-package.zip
          asset_content_type: application/zip
